version: '3.4'

services:
  api:
    build: .
    command: npm run start:dev
    restart: always
    environment:
      - FORCE_COLOR=3
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14.2-alpine3.15
    env_file:
      - .env
    restart: always
    volumes:
      - ./db-volume/postdb-data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always

volumes:
  db-volume:
    driver: local

networks:
  default:
    external:
      name: local-docker-network
